import Header from '@/components/Header'
import { inter } from '../../public/fonts/Fonts'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} font-sans`}>
      {/* <body>{children}</body> */}
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
